# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD:ruby/Makefile 430586 2017-01-04 19:09:37Z swills $

PORTNAME=	rack-openid
PORTVERSION=	1.4.2
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Provides a more HTTPish API around the ruby-openid library


RUN_DEPENDS=	rubygem-rack16>=1.6:ruby/rubygem-rack16 \
		rubygem-ruby-openid>=2.1.8:ruby/rubygem-ruby-openid

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
