# $FreeBSD: head/comms/rubygem-ruby-termios/Makefile 430329 2017-01-02 09:55:42Z swills $

PORTNAME=	ruby-termios
PORTVERSION=	1.0.2
CATEGORIES=	comms rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby interface to termios


USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
