# $FreeBSD: head/devel/rubygem-googleapis-common-protos-types/Makefile 513073 2019-09-27 21:27:37Z sunpoet $

PORTNAME=	googleapis-common-protos-types
PORTVERSION=	1.0.4
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Common protocol buffer types used by Google APIs

RUN_DEPENDS=	rubygem-google-protobuf>=3.0:ruby/rubygem-google-protobuf

USES=		gem
USE_RUBY=	yes

NO_ARCH=	yes

.include <bsd.port.mk>
