#
# $Id$
#
PORTNAME=	php-mod
PORTVERSION=	7.1.21
CATEGORIES=	lang

MAINTAINER=	php@FreeBSD.org
COMMENT=	meta-port PHP

USES=	metaport

BUILD_DEPENDS+= php71-mod-opcache>0:php71/php-mod-opcache
BUILD_DEPENDS+= php71-mod-bcmath>0:php71/php-mod-bcmath
BUILD_DEPENDS+= php71-mod-bz2>0:php71/php-mod-bz2
BUILD_DEPENDS+= php71-mod-calendar>0:php71/php-mod-calendar
BUILD_DEPENDS+= php71-mod-ctype>0:php71/php-mod-ctype
BUILD_DEPENDS+= php71-mod-curl>0:php71/php-mod-curl
BUILD_DEPENDS+= php71-mod-dba>0:php71/php-mod-dba
BUILD_DEPENDS+= php71-mod-enchant>0:php71/php-mod-enchant
BUILD_DEPENDS+= php71-mod-exif>0:php71/php-mod-exif
BUILD_DEPENDS+= php71-mod-fileinfo>0:php71/php-mod-fileinfo
BUILD_DEPENDS+= php71-mod-filter>0:php71/php-mod-filter
BUILD_DEPENDS+= php71-mod-ftp>0:php71/php-mod-ftp
BUILD_DEPENDS+= php71-mod-gd>0:php71/php-mod-gd
BUILD_DEPENDS+= php71-mod-gettext>0:php71/php-mod-gettext
BUILD_DEPENDS+= php71-mod-gmp>0:php71/php-mod-gmp
BUILD_DEPENDS+= php71-mod-hash>0:php71/php-mod-hash
BUILD_DEPENDS+= php71-mod-iconv>0:php71/php-mod-iconv
BUILD_DEPENDS+= php71-mod-imap>0:php71/php-mod-imap
BUILD_DEPENDS+= php71-mod-intl>0:php71/php-mod-intl
BUILD_DEPENDS+= php71-mod-json>0:php71/php-mod-json
BUILD_DEPENDS+= php71-mod-mbstring>0:php71/php-mod-mbstring
BUILD_DEPENDS+= php71-mod-mcrypt>0:php71/php-mod-mcrypt

BUILD_DEPENDS+= php71-mod-phar>0:php71/php-mod-phar

BUILD_DEPENDS+= php71-mod-mysqli>0:php71/php-mod-mysqli
###BUILD_DEPENDS+= php71-mod-mysqlnd>0:php71/php-mod-mysqlnd
BUILD_DEPENDS+= php71-mod-openssl>0:php71/php-mod-openssl
BUILD_DEPENDS+= php71-mod-pcntl>0:php71/php-mod-pcntl
BUILD_DEPENDS+= php71-mod-pdo>0:php71/php-mod-pdo
BUILD_DEPENDS+= php71-mod-pdo_mysql>0:php71/php-mod-pdo_mysql
BUILD_DEPENDS+= php71-mod-pdo_pgsql>0:php71/php-mod-pdo_pgsql
BUILD_DEPENDS+= php71-mod-pdo_sqlite>0:php71/php-mod-pdo_sqlite
BUILD_DEPENDS+= php71-mod-pgsql>0:php71/php-mod-pgsql
BUILD_DEPENDS+= php71-mod-posix>0:php71/php-mod-posix
BUILD_DEPENDS+= php71-mod-pspell>0:php71/php-mod-pspell
###BUILD_DEPENDS+= php71-mod-readline>0:php71/php-mod-readline
BUILD_DEPENDS+= php71-mod-recode>0:php71/php-mod-recode
BUILD_DEPENDS+= php71-mod-session>0:php71/php-mod-session
BUILD_DEPENDS+= php71-mod-shmop>0:php71/php-mod-shmop
BUILD_DEPENDS+= php71-mod-simplexml>0:php71/php-mod-simplexml
BUILD_DEPENDS+= php71-mod-snmp>0:php71/php-mod-snmp
BUILD_DEPENDS+= php71-mod-soap>0:php71/php-mod-soap
BUILD_DEPENDS+= php71-mod-sockets>0:php71/php-mod-sockets
BUILD_DEPENDS+= php71-mod-sqlite3>0:php71/php-mod-sqlite3
BUILD_DEPENDS+= php71-mod-sysvmsg>0:php71/php-mod-sysvmsg
BUILD_DEPENDS+= php71-mod-sysvsem>0:php71/php-mod-sysvsem
BUILD_DEPENDS+= php71-mod-sysvshm>0:php71/php-mod-sysvshm
BUILD_DEPENDS+= php71-mod-tokenizer>0:php71/php-mod-tokenizer
BUILD_DEPENDS+= php71-mod-wddx>0:php71/php-mod-wddx
BUILD_DEPENDS+= php71-mod-xmlreader>0:php71/php-mod-xmlreader
BUILD_DEPENDS+= php71-mod-xmlrpc>0:php71/php-mod-xmlrpc
BUILD_DEPENDS+= php71-mod-xmlwriter>0:php71/php-mod-xmlwriter
BUILD_DEPENDS+= php71-mod-xsl>0:php71/php-mod-xsl
BUILD_DEPENDS+= php71-mod-zip>0:php71/php-mod-zip

BUILD_DEPENDS+= php71-mod-zlib>0:php71/php-mod-zlib
BUILD_DEPENDS+= php71-mod-xml>0:php71/php-mod-xml
BUILD_DEPENDS+= php71-mod-dom>0:php71/php-mod-dom


.include <bsd.port.mk>
#EOF
