#
# $Id$
#
PORTNAME=	IO-stringy
PORTVERSION=	2.111
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Use IO handles with non-file objects

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
#EOF
