#
# $Id$
#
PORTNAME=	isoqlog
PORTVERSION=	2.2.1
CATEGORIES=	mail
MASTER_SITES+=	http://www.enderunix.org/isoqlog/
MASTER_SITES+=	http://www.trunix.org/projeler/isoqlog/
MASTER_SITES+=	http://www.acikkod.org/softwares/

MAINTAINER=	dbaio@bsd.com.br
COMMENT=	Qmail, postfix, sendmail, exim MTA log analysis program

GNU_CONFIGURE=	yes
USES=	gmake

SUB_FILES=	pkg-message

.include <bsd.port.mk>
#EOF
