# Created by: Johannes Dieterich <jmd@FreeBSD.org>
# $FreeBSD: head/graphics/gpu-firmware-kmod/Makefile 514545 2019-10-15 16:23:05Z jmd $

PORTNAME=	gpu-firmware-kmod
PORTVERSION=	g20210330

CATEGORIES=	graphics

MAINTAINER=	jmd@FreeBSD.org
COMMENT=	Firmware modules for the linuxkpi-based KMS components

USES=		kmod uidfix

USE_GITHUB=	yes
GH_ACCOUNT=	freebsd
GH_PROJECT=	drm-kmod-firmware
GH_TAGNAME=	df9e66d

.include <bsd.port.mk>
