# Created by: Eric Freeman <freebsdports@chillibear.com>
# $FreeBSD: head/textproc/rubygem-loofah/Makefile 515294 2019-10-23 17:46:09Z sunpoet $

PORTNAME=	loofah
PORTVERSION=	2.3.1
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Library for manipulating HTML/XML documents and fragments


RUN_DEPENDS=	rubygem-crass>=1.0.2:ruby/rubygem-crass \
		rubygem-nokogiri>=1.5.9:ruby/rubygem-nokogiri

USES=		gem
USE_RUBY=	yes

NO_ARCH=	yes

.include <bsd.port.mk>
