# Created by: Steven Kreuzer <skreuzer@FreeBSD.org>

PORTNAME=	Mojolicious-Plugin-YamlConfig
PORTVERSION=	0.2.1
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	YAML Configuration Plugin

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS=	p5-Mojolicious>=5.54:perl/p5-Mojolicious \
		p5-YAML-Tiny>=1.60:perl/p5-YAML-Tiny
TEST_DEPENDS=	p5-Test-Compile>=0:perl/p5-Test-Compile

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
