--- ./magick/magick-config.h.orig	2015-10-31 14:18:20.000000000 +0200
+++ ./magick/magick-config.h	2015-11-05 14:39:08.381329000 +0200
@@ -107,7 +107,7 @@
  
 /* module dir */
 #ifndef MAGICKCORE_MODULES_DIRNAME
-# define MAGICKCORE_MODULES_DIRNAME MAGICKCORE_MODULES_BASEDIRNAME "-" MAGICKCORE_ABI_SUFFIX
+# define MAGICKCORE_MODULES_DIRNAME MAGICKCORE_MODULES_BASEDIRNAME
 #endif
  
 #ifndef MAGICKCORE_MODULES_PATH
@@ -146,7 +146,7 @@
 
 /* sharearch dir */
 #ifndef MAGICKCORE_SHAREARCH_DIRNAME
-# define MAGICKCORE_SHAREARCH_DIRNAME MAGICKCORE_SHAREARCH_BASEDIRNAME "-" MAGICKCORE_ABI_SUFFIX
+# define MAGICKCORE_SHAREARCH_DIRNAME MAGICKCORE_SHAREARCH_BASEDIRNAME
 #endif
  
 #ifndef MAGICKCORE_SHAREARCH_PATH
