# Created by: Joseph Benden <joe@thrallingpenguin.com>
# $FreeBSD: head/devel/rubygem-nori/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	nori
PORTVERSION=	2.6.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	joe@thrallingpenguin.com
COMMENT=	Library for converting XML to Hash syntax

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
