# $FreeBSD: head/net/rubygem-net-ping/Makefile 510024 2019-08-27 20:09:22Z romain $

PORTNAME=	rping
PORTVERSION=	0.1.4
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Collection of classes that provide different ways to ping computers

USES=		gem
USE_RUBY=	yes

.include <bsd.port.mk>
