#
# $FreeBSD$
#
PORTNAME=	dedup
PORTVERSION=	0.1
CATEGORIES=	misc

MAINTAINER=	onborodin@gmail.com
COMMENT=	Utilite fot search for files with the same content

BUILD_DEPENDS = go:lang/go

GNU_CONFIGURE=	yes
USES=		gmake

USE_GITHUB=	yes
GH_ACCOUNT=	kindsoldier
GH_PROJECT=	dedup

.include <bsd.port.mk>
