#
# $Id$
#
PORTNAME=	Regexp-Grammars
PORTVERSION=	1.045
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	citric@cubicone.tmetic.com
COMMENT=	Add grammatical parsing features to Perl 5.10 regexes

USES=		perl5
#USE_PERL5=	modbuild
USE_PERL5=	configure

.include <bsd.port.mk>
#EOF
