# Created by: Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/textproc/rubygem-sassc/Makefile 515060 2019-10-20 17:21:41Z sunpoet $

PORTNAME=	sassc
PORTVERSION=	2.2.1
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Use libsass with Ruby

RUN_DEPENDS=	rubygem-ffi>=1.9:ruby/rubygem-ffi

USES=		gem gmake
USE_RUBY=	yes

.include <bsd.port.mk>
