# $FreeBSD: head/www/rubygem-rack-test/Makefile 508795 2019-08-12 19:47:14Z sunpoet $

PORTNAME=	rack-test
PORTVERSION=	1.1.0
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Small, simple testing API for Rack apps

RUN_DEPENDS=	rubygem-rack>=1.0:ruby/rubygem-rack

USES=		gem
USE_RUBY=	yes

NO_ARCH=	yes

.include <bsd.port.mk>
