#
# $Id$
#
PORTNAME=	tmpreaper
PORTVERSION=	1.6.13
CATEGORIES=	sysutils
MASTER_SITES=	CRITICAL

MAINTAINER=	ziggi@inbox.ru
COMMENT=	Cleans up files in directories based on their age

GNU_CONFIGURE=	yes
USES+=		gmake
MAKE_JOBS_SAFE=	yes

PLIST_FILES+=	sbin/tmpreaper
PLIST_FILES+=	man/man8/tmpreaper.8.gz

.include <bsd.port.mk>
#EOF

