# Created by: Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-google-protobuf/Makefile 516076 2019-10-30 15:41:46Z sunpoet $

PORTNAME=	google-protobuf
PORTVERSION=	3.10.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Ruby extension to Google Protocol Buffers

USES=		gem
USE_RUBY=	yes

.include <bsd.port.mk>
