# $FreeBSD: head/www/rubygem-rack-accept/Makefile 427857 2016-12-05 07:19:53Z sunpoet $

PORTNAME=	rack-accept
PORTVERSION=	0.4.5
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	HTTP Accept* for Ruby/Rack


RUN_DEPENDS=	rubygem-rack>=0.4:ruby/rubygem-rack

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
