#
# $Id$
#
PORTNAME=       roo
PORTVERSION=    2.8.2
CATEGORIES=     rubygems
MAINTAINER=     none@FreeBSD.org
MASTER_SITES=   RG
COMMENT=       Roo can access the contents of various spreadsheet files.

RUN_DEPENDS+= rubygem-nokogiri>=1:ruby/rubygem-nokogiri
RUN_DEPENDS+= rubygem-rubyzip>=1.2.1:ruby/rubygem-rubyzip

USES=           gem
USE_RUBY=       yes

NO_ARCH=        yes

.include <bsd.port.mk>
#EOF
