# Created by: Michael Moll <kvedulv at kvedulv.de>
# $FreeBSD: head/devel/rubygem-byebug/Makefile 506678 2019-07-15 17:44:12Z sunpoet $

PORTNAME=	byebug
PORTVERSION=	11.0.1
CATEGORIES=	devel ruby
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Ruby 2 debugger

USES=		gem
USE_RUBY=	yes

PLIST_FILES=	bin/byebug

.include <bsd.port.mk>
