#
# $Id$
#
PORTNAME=	libconfuse
PORTVERSION=	2.7
CATEGORIES=	devel
MASTER_SITES=	SAVANNAH/confuse
DISTNAME=	confuse-${PORTVERSION}

MAINTAINER=	otis@freebsd.sk
COMMENT=	Configuration file parsing library

GNU_CONFIGURE=	yes
CONFIGURE_ARGS=	--disable-nls --enable-shared
INSTALL_TARGET=	install-strip
USES=		pathfix pkgconfig
USE_LDCONFIG=	yes

.include <bsd.port.mk>
#EOF
