PORTNAME=	scons
PORTVERSION=	4.3.0
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMESUFFIX=	${PYTHON_PKGNAMESUFFIX}
DISTNAME=	SCons-${PORTVERSION}

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Build tool alternative to make
WWW=		https://scons.org/

USES=		python:3.6+
USE_PYTHON=	autoplist concurrent distutils

NO_ARCH=	yes

.include <bsd.port.mk>
