# Created by: Akinori MUSHA aka knu <knu@idaemons.org>
# $FreeBSD: head/devel/rubygem-locale/Makefile 457207 2017-12-25 05:25:00Z knu $

PORTNAME=	locale
PORTVERSION=	2.1.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	knu@FreeBSD.org
COMMENT=	Pure ruby library to support locales

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
