#
# $Id$
#
PORTNAME=	re2c
PORTVERSION=	4.1
CATEGORIES=	devel

MAINTAINER=	chalpin@cs.wisc.edu
COMMENT=	Compile regular expression to C (much faster final code than flex)

USES=		cmake gmake compiler:c++11-lib cpe python:test shebangfix tar:xz

MANPREFIX= ${PREFIX}/share


.include <bsd.port.mk>
#EOF
