# Created by: Kubilay Kocak <koobs@FreeBSD.org>
# $FreeBSD: head/dns/py-idna/Makefile 400660 2015-11-02 16:30:46Z koobs $

PORTNAME=	idna
PORTVERSION=	2.7
CATEGORIES=	dns python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	koobs@FreeBSD.org
COMMENT=	Internationalized Domain Names in Applications (IDNA)

USES=		python
USE_PYTHON=	autoplist distutils


.include <bsd.port.mk>
#EOF
