# $FreeBSD: head/devel/rubygem-faker/Makefile 515014 2019-10-20 17:17:53Z sunpoet $

PORTNAME=	faker
PORTVERSION=	2.7.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Library for generating fake data: names, addresses, phone numbers

RUN_DEPENDS=	rubygem-i18n>=1.6:ruby/rubygem-i18n

USES=		gem
USE_RUBY=	yes

NO_ARCH=	yes

PLIST_FILES=	bin/faker

.include <bsd.port.mk>
