# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD:ruby/Makefile 448735 2017-08-25 18:21:43Z sunpoet $

PORTNAME=	addressable
PORTVERSION=	2.5.2
CATEGORIES=	www devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Replacement for the URI implementation


RUN_DEPENDS=	rubygem-public_suffix>=2.0.2:ruby/rubygem-public_suffix

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
