#!/bin/sh
set -x

PREFIX=${PKG_PREFIX}

case $2 in 
    PRE-INSTALL)
	install -d -o root -g wheel -m 0750 /var/db/sudo
	install -d -o root -g wheel -m 0750 /var/run/sudo
	install -d -o root -g wheel -m 0750 ${PREFIX}/etc/sudoers.d
	;;
    POST-INSTALL)
	;;
esac
#EOF
