#
# $Id$$
#
PORTNAME=	xfce4-wm-themes
PORTVERSION=	4.10.0
#PORTEPOCH=	12
CATEGORIES=	misc xfce

MASTER_SITES=	${MASTER_SITE_XFCE}
MASTER_SITE_SUBDIR=	src/art/xfwm4-themes/${PORTVERSION:R}
DISTNAME=	xfwm4-themes-${PORTVERSION}

MAINTAINER=	onborodin@gmail.com
COMMENT=	XFce 4 window decoration themes for xfwm4

GNU_CONFIGURE=	yes
USER_GMAKE=	yes
USES+=		tar:bzip2

.include <bsd.port.mk>
#EOF
