#
# $Id$
#
PORTNAME=	graphite2
PORTVERSION=	1.3.10
CATEGORIES=	graphics print
#MASTER_SITES=	http://projects.palaso.org/attachments/download/434/ SF/silgraphite/${PORTNAME}
PKGNAMEPREFIX=	lib

USE_GITHUB=	yes
GH_ACCOUNT=	silnrsi
GH_PROJECT=	graphite


MAINTAINER=	office@FreeBSD.org
COMMENT=	Rendering capabilities for complex non-Roman writing systems

USES=		cmake tar:tgz
USE_LDCONFIG=	yes

.include <bsd.port.mk>
#EOF
