# Created by: Bartek Rutkowski <ports@robakdesign.com>
# $FreeBSD: head/devel/py-click/Makefile 496503 2019-03-21 19:41:43Z sunpoet $

PORTNAME=	click
PORTVERSION=	7.0
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	Click-${PORTVERSION}

MAINTAINER=	robak@FreeBSD.org
COMMENT=	Python package for creating command line interfaces

USES=		python
USE_PYTHON=	distutils autoplist

NO_ARCH=	yes

.include <bsd.port.mk>
