# Created by: Torsten Zuehlsdorff <tz@FreeBSD.org>
# $FreeBSD: head/www/rubygem-turbolinks-source/Makefile 508641 2019-08-11 16:50:42Z sunpoet $

PORTNAME=	turbolinks-source
PORTVERSION=	5.2.0
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Turbolinks JavaScript assets

USES=		gem
USE_RUBY=	yes

NO_ARCH=	yes

.include <bsd.port.mk>
