# Created by: will
# $FreeBSD: head/math/p5-Bit-Vector/Makefile 412348 2016-04-01 14:17:44Z mat $

PORTNAME=	Bit-Vector
PORTVERSION=	7.4
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Library of advanced math functions that includes a Perl OO module

BUILD_DEPENDS=	p5-Carp-Clan>=5.3:perl/p5-Carp-Clan
RUN_DEPENDS:=	${BUILD_DEPENDS}

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
#EOF
