#
# $Id$
#
PORTNAME=       aws-partitions
PORTVERSION=    1.242.0
CATEGORIES=     rubygems
MAINTAINER=     none@FreeBSD.org
MASTER_SITES=   RG
COMMENT=       Provides information about AWS partitions, regions, and services.


USES=           gem
USE_RUBY=       yes

NO_ARCH=        yes

.include <bsd.port.mk>
#EOF
