#
# $Id$
#
PORTNAME=	Image-ExifTool
PORTVERSION=	10.15
CATEGORIES=	graphics perl5
MASTER_SITES=	http://www.sno.phy.queensu.ca/~phil/exiftool/ CPAN
MASTER_SITE_SUBDIR=	CPAN:EXIFTOOL
PKGNAMEPREFIX=	p5-

MAINTAINER=	devin@spamcop.net
COMMENT=	Perl module for getting EXIF data from image files

CONFLICTS=	p5-Image-ExifTool-devel-[0-9]*

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
#EOF
