# $FreeBSD: head/net-mgmt/rubygem-snmp/Makefile 457912 2018-01-02 16:20:08Z swills $

PORTNAME=	netsnmp
PORTVERSION=	0.1.9
CATEGORIES=	net-mgmt rubygems
MASTER_SITES=	RG

MAINTAINER=	mhjacks@swbell.net
COMMENT=	SNMP library for Ruby

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
