# $FreeBSD: head/devel/rubygem-font-awesome-rails/Makefile 499170 2019-04-17 11:03:29Z mfechner $

PORTNAME=	font-awesome-sass
PORTVERSION=	5.9.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Provides the Font-Awesome web fonts and stylesheets as a Rails engine

RUN_DEPENDS=	rubygem-sassc>=0:ruby/rubygem-sassc

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
