# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD:ruby/Makefile 449072 2017-09-01 10:51:13Z sunpoet $

PORTNAME=	sprockets-rails
PORTVERSION=	3.2.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Sprockets Rails integration


RUN_DEPENDS?=	rubygem-actionpack4>=4.0:ruby/rubygem-actionpack4 \
		rubygem-activesupport4>=4.0:ruby/rubygem-activesupport4 \
		rubygem-sprockets3>=3.0.0:ruby/rubygem-sprockets3

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
