#
# $Id$
#
PORTNAME=	YAML
PORTVERSION=	1.14
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	YAML implementation in Perl

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
#EOF
