#
# $Id$
#
PORTNAME=	IO-Tty
PORTVERSION=	1.12
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Flexible I/O Perl5 module that allows manipulation of pseudo-TTYs

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
#EOF
