# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/devel/p5-Sub-Exporter-Progressive/Makefile 425556 2016-11-06 16:50:56Z sunpoet $

PORTNAME=	Sub-Exporter-Progressive
PORTVERSION=	0.001013
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Only use Sub::Exporter if you need it

BUILD_DEPENDS=	p5-Sub-Exporter>=0:perl/p5-Sub-Exporter
RUN_DEPENDS:=	${BUILD_DEPENDS}

NO_ARCH=	yes
USE_PERL5=	configure
USES=		perl5

.include <bsd.port.mk>
