#
# $Id$
#
PORTNAME=       aws-sdk-core
PORTVERSION=    3.80.0
CATEGORIES=     rubygems
MAINTAINER=     none@FreeBSD.org
MASTER_SITES=   RG
COMMENT=       AWS SDK for Ruby - Core

RUN_DEPENDS+= rubygem-jmespath>=1.0:ruby/rubygem-jmespath
RUN_DEPENDS+= rubygem-aws-partitions>=1.239.0:ruby/rubygem-aws-partitions
RUN_DEPENDS+= rubygem-aws-sigv4>=1.1:ruby/rubygem-aws-sigv4
RUN_DEPENDS+= rubygem-aws-eventstream>=1.0.2:ruby/rubygem-aws-eventstream

USES=           gem
USE_RUBY=       yes

NO_ARCH=        yes

.include <bsd.port.mk>
#EOF
