# Created by: Eric Freeman <freebsdports@chillibear.com>
# $FreeBSD: head/textproc/rubygem-terminal-table/Makefile 511473 2019-09-07 22:47:07Z sunpoet $

PORTNAME=	terminal-table
PORTVERSION=	1.8.0
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Simple, feature rich ASCII table generation library

RUN_DEPENDS=	rubygem-unicode-display_width>=1.1.1:ruby/rubygem-unicode-display_width

USES=		gem
USE_RUBY=	yes

NO_ARCH=	yes

.include <bsd.port.mk>
