#
# $Id$
#
PORTNAME=	php-mod
PORTVERSION=	7.2.24
CATEGORIES=	lang

MAINTAINER=	php@FreeBSD.org
COMMENT=	meta-port PHP

USES=	metaport

VER= ${PORTVERSION:R:S/.//g}

BUILD_DEPENDS+= php${VER}-mod-opcache>0:php72/php-mod-opcache
BUILD_DEPENDS+= php${VER}-mod-bcmath>0:php72/php-mod-bcmath
BUILD_DEPENDS+= php${VER}-mod-bz2>0:php72/php-mod-bz2
BUILD_DEPENDS+= php${VER}-mod-calendar>0:php72/php-mod-calendar
BUILD_DEPENDS+= php${VER}-mod-ctype>0:php72/php-mod-ctype
BUILD_DEPENDS+= php${VER}-mod-curl>0:php72/php-mod-curl
BUILD_DEPENDS+= php${VER}-mod-dba>0:php72/php-mod-dba
BUILD_DEPENDS+= php${VER}-mod-enchant>0:php72/php-mod-enchant
BUILD_DEPENDS+= php${VER}-mod-exif>0:php72/php-mod-exif
BUILD_DEPENDS+= php${VER}-mod-fileinfo>0:php72/php-mod-fileinfo
BUILD_DEPENDS+= php${VER}-mod-filter>0:php72/php-mod-filter
BUILD_DEPENDS+= php${VER}-mod-ftp>0:php72/php-mod-ftp
BUILD_DEPENDS+= php${VER}-mod-gd>0:php72/php-mod-gd
BUILD_DEPENDS+= php${VER}-mod-gettext>0:php72/php-mod-gettext
BUILD_DEPENDS+= php${VER}-mod-gmp>0:php72/php-mod-gmp
BUILD_DEPENDS+= php${VER}-mod-hash>0:php72/php-mod-hash
BUILD_DEPENDS+= php${VER}-mod-iconv>0:php72/php-mod-iconv
BUILD_DEPENDS+= php${VER}-mod-imap>0:php72/php-mod-imap
BUILD_DEPENDS+= php${VER}-mod-intl>0:php72/php-mod-intl
BUILD_DEPENDS+= php${VER}-mod-json>0:php72/php-mod-json
BUILD_DEPENDS+= php${VER}-mod-mbstring>0:php72/php-mod-mbstring
#BUILD_DEPENDS+= php${VER}-mod-mcrypt>0:php72/php-mod-mcrypt
##BUILD_DEPENDS+= php${VER}-mod-mysqli>0:php72/php-mod-mysql
BUILD_DEPENDS+= php${VER}-mod-mysqli>0:php72/php-mod-mysqli
###BUILD_DEPENDS+= php${VER}-mod-mysqlnd>0:php72/php-mod-mysqlnd
BUILD_DEPENDS+= php${VER}-mod-openssl>0:php72/php-mod-openssl
BUILD_DEPENDS+= php${VER}-mod-pcntl>0:php72/php-mod-pcntl

BUILD_DEPENDS+= php${VER}-mod-phar>0:php72/php-mod-phar

BUILD_DEPENDS+= php${VER}-mod-pdo>0:php72/php-mod-pdo
BUILD_DEPENDS+= php${VER}-mod-pdo_mysql>0:php72/php-mod-pdo_mysql
BUILD_DEPENDS+= php${VER}-mod-pdo_pgsql>0:php72/php-mod-pdo_pgsql
BUILD_DEPENDS+= php${VER}-mod-pdo_sqlite>0:php72/php-mod-pdo_sqlite
BUILD_DEPENDS+= php${VER}-mod-pgsql>0:php72/php-mod-pgsql
BUILD_DEPENDS+= php${VER}-mod-posix>0:php72/php-mod-posix
BUILD_DEPENDS+= php${VER}-mod-pspell>0:php72/php-mod-pspell
###BUILD_DEPENDS+= php${VER}-mod-readline>0:php72/php-mod-readline
BUILD_DEPENDS+= php${VER}-mod-recode>0:php72/php-mod-recode
BUILD_DEPENDS+= php${VER}-mod-session>0:php72/php-mod-session
BUILD_DEPENDS+= php${VER}-mod-shmop>0:php72/php-mod-shmop
BUILD_DEPENDS+= php${VER}-mod-simplexml>0:php72/php-mod-simplexml
BUILD_DEPENDS+= php${VER}-mod-snmp>0:php72/php-mod-snmp
BUILD_DEPENDS+= php${VER}-mod-soap>0:php72/php-mod-soap
BUILD_DEPENDS+= php${VER}-mod-sockets>0:php72/php-mod-sockets
BUILD_DEPENDS+= php${VER}-mod-sqlite3>0:php72/php-mod-sqlite3
BUILD_DEPENDS+= php${VER}-mod-sysvmsg>0:php72/php-mod-sysvmsg
BUILD_DEPENDS+= php${VER}-mod-sysvsem>0:php72/php-mod-sysvsem
BUILD_DEPENDS+= php${VER}-mod-sysvshm>0:php72/php-mod-sysvshm
BUILD_DEPENDS+= php${VER}-mod-tokenizer>0:php72/php-mod-tokenizer
BUILD_DEPENDS+= php${VER}-mod-wddx>0:php72/php-mod-wddx
BUILD_DEPENDS+= php${VER}-mod-xmlreader>0:php72/php-mod-xmlreader
BUILD_DEPENDS+= php${VER}-mod-xmlrpc>0:php72/php-mod-xmlrpc
BUILD_DEPENDS+= php${VER}-mod-xmlwriter>0:php72/php-mod-xmlwriter
BUILD_DEPENDS+= php${VER}-mod-xsl>0:php72/php-mod-xsl
BUILD_DEPENDS+= php${VER}-mod-zip>0:php72/php-mod-zip

BUILD_DEPENDS+= php${VER}-mod-zlib>0:php72/php-mod-zlib
BUILD_DEPENDS+= php${VER}-mod-xml>0:php72/php-mod-xml
BUILD_DEPENDS+= php${VER}-mod-dom>0:php72/php-mod-dom

BUILD_DEPENDS+= php${VER}-mod-ldap>0:php72/php-mod-ldap


.include <bsd.port.mk>
#EOF
