#
# $Id$
#
PORTNAME=	Mail
DISTVERSION=	1.2.0
CATEGORIES=	mail www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	PEAR class that provides multiple interfaces for sending emails

#OPTIONS_DEFINE=	PEAR_NET_SMTP
#PEAR_NET_SMTP_DESC=	PEAR::Net_SMTP support

USES=	pear

RUN_DEPENDS=	${PEARDIR}/Net/SMTP.php:pear/pear-Net_SMTP

.include <bsd.port.mk>
#EOF
