# $FreeBSD: head/devel/rubygem-hocon/Makefile 515715 2019-10-26 17:30:04Z romain $

PORTNAME=	hocon
PORTVERSION=	1.2.6
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	puppet@FreeBSD.org
COMMENT=	Ruby port of the Typesafe Config library

USES=		gem
USE_RUBY=	yes

PLIST_FILES=	bin/hocon

.include <bsd.port.mk>
