#
# $Id$
#
PORTNAME=	AnyEvent
PORTVERSION=	7.14
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Provide framework for multiple event loops

BUILD_DEPENDS=	p5-Canary-Stability>=0:perl/p5-Canary-Stability
#TEST_DEPENDS=	p5-Net-SSLeay>=0:security/p5-Net-SSLeay

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
#EOF
