# Created by: Dikshie <dikshie@sfc.wide.ad.jp>
# $FreeBSD: head/www/p5-Mojo-Server-FastCGI/Makefile 412351 2016-04-01 14:33:55Z mat $

PORTNAME=	Mojo-ACME
PORTVERSION=	0.09
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:JBERGER
MASTER_SITES+=  https://cpan.metacpan.org/authors/id/J/JB/JBERGER/ #Mojo-ACME-0.09.tar.gz
PKGNAMEPREFIX=	p5-

MAINTAINER=	dikshie@sfc.wide.ad.jp
COMMENT=	Mojo Server FastCGI

RUN_DEPENDS=	p5-Mojolicious>=3.21:perl/p5-Mojolicious

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
#EOF
