# Created by: Andrey Kostenko <andrey@kostenko.name>
# $FreeBSD: head/devel/p5-IO-Interactive/Makefile 407761 2016-02-01 19:49:10Z sunpoet $

PORTNAME=	IO-Interactive
PORTVERSION=	1.022
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Utilities for interactive I/O


NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
#EOF
