# Created by: Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-zeitwerk/Makefile 511461 2019-09-07 22:46:06Z sunpoet $

PORTNAME=	zeitwerk
PORTVERSION=	2.2.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Efficient and thread-safe code loader


USES=		gem
USE_RUBY=	yes

NO_ARCH=	yes

.include <bsd.port.mk>
