# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-xpath/Makefile 441795 2017-05-26 16:49:28Z sunpoet $

PORTNAME=	xpath
PORTVERSION=	2.1.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	DSL for generating XPath Expressions


RUN_DEPENDS=	rubygem-nokogiri>=1.3:ruby/rubygem-nokogiri

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
