# Created by: Daniel Roethlisberger <daniel@roe.ch>
# $FreeBSD: head/www/rubygem-sinatra/Makefile 441035 2017-05-16 18:21:55Z sunpoet $

PORTNAME=	semantic_logger
PORTVERSION=	4.2.0
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Low latency, high throughput, enterprise-scale logging system for Ruby.

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
