# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD:ruby/Makefile 460101 2018-01-27 10:24:51Z sunpoet $

PORTNAME=	minitest
PORTVERSION=	5.11.3
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Minitest provides a complete suite of testing facilities


NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
