#
# $Id$
#
PORTNAME=	pwm
PORTVERSION=	0.01.2
CATEGORIES=	security perl5

MAINTAINER=	borodin@unix7.org
COMMENT=	flat-file password manager

USE_GITHUB=     yes
GH_ACCOUNT=     onborodin
GH_PROJECT=     ${PORTNAME}

USES=		perl5 tar:xz
GNU_CONFIGURE=	yes
CONFIGURE_ARGS+= --mandir=${PREFIX}/man

.include <bsd.port.mk>
#EOF
