# $FreeBSD: head/graphics/p5-GD/Makefile 412346 2016-04-01 14:00:51Z mat $

PORTNAME=	GD
PORTVERSION=	2.56
CATEGORIES=	graphics perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl5 interface to Gd Graphics Library version2


LIB_DEPENDS=	libgd.so:graph/libgd

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
#EOF
