#!/bin/sh

set -x

PREFIX=${PKG_PREFIX}
LOCALBASE=${PKG_PREFIX}

case $2 in 
    PRE-INSTALL)
	;;
    POST-INSTALL)
#	install  -d -m 1777 -o root -g wheel /var/texmf
#	${PREFIX}/bin/texconfig-sys rehash
#	${PREFIX}/bin/texconfig-sys init
	;;
esac
#EOF
