# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-hamster/Makefile 430045 2016-12-30 19:22:08Z sunpoet $

PORTNAME=	hamster
PORTVERSION=	3.0.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Efficient, immutable, thread-safe collection classes for Ruby

RUN_DEPENDS=	rubygem-concurrent-ruby>=1.0:ruby/rubygem-concurrent-ruby

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
