# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD:perl/Makefile 412347 2016-04-01 14:08:37Z mat $

PORTNAME=	Try-Tiny
PORTVERSION=	0.28
CATEGORIES=	lang perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:ETHER
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Minimal try/catch with proper localization of $$@


USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
#EOF

