# Created by: Christoph Kick
# $FreeBSD: head/devel/rubygem-ffi/Makefile 502233 2019-05-21 18:04:27Z sunpoet $

PORTNAME=	ffi
PORTVERSION=	1.11.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Extension for dynamic libraries & binding functions

LIB_DEPENDS=	libffi.so:devel/libffi

USES=		gem
USE_RUBY=	yes

.include <bsd.port.mk>
