#
# $Id$
#
PORTNAME=	Class-Inspector
PORTVERSION=	1.28
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Provides information about classes

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
#EOF
