PORTNAME=	gmake
PORTVERSION=	4.3
CATEGORIES=	devel
MASTER_SITES=	GNU/make
DISTNAME=	make-${PORTVERSION}

MAINTAINER=	tijl@FreeBSD.org
COMMENT=	GNU version of 'make' utility

GNU_CONFIGURE=	yes
CONFIGURE_ARGS=	--program-prefix=g --without-guile

USES=		cpe tar:lz
CPE_VENDOR=	gnu
CPE_PRODUCT=	make

.include <bsd.port.mk>
