#
# $Id$
#
PORTNAME=	Proc-Daemon
PORTVERSION=	0.21
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	lth@FreeBSD.org
COMMENT=	Perl module that provides a method to daemonify a Perl script

TEST_DEPENDS=	p5-Proc-ProcessTable>0:perl/p5-Proc-ProcessTable

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
#EOF
