# Created by: James FitzGibbon <jfitz@FreeBSD.org>
# $FreeBSD: head/graphics/p5-Image-Size/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Image-Size
PORTVERSION=	3.232
CATEGORIES=	graphics www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tolid@tolid.eu.org
COMMENT=	Perl5 module to determine the size of images in several common formats

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
#EOF
