#
# $Id$
#
PORTNAME=	Net_DIME
PORTVERSION=	1.0.2
CATEGORIES=	net pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	The PEAR::Net_DIME class implements DIME encoding

USES=	pear

.include <bsd.port.mk>
#EOF
