#
# $id$
#
PORTNAME=	SNMP-Simple
PORTVERSION=	0.02
CATEGORIES=	net-mgmt perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Shortcuts for when using p5-SNMP

RUN_DEPENDS=	net-snmp>=0:net/net-snmp

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
#EOF
