#
# $Id$
#
PORTNAME=	IO-Socket-IP
PORTVERSION=	0.37
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Drop-in replacement for IO::Socket::INET supporting IPv4 and IPv6

BUILD_DEPENDS=	p5-Socket>=1.97:perl/p5-Socket
RUN_DEPENDS:=	${BUILD_DEPENDS}

USE_PERL5=	configure
USES=		perl5

.include <bsd.port.mk>
#EOF
