#
# $Id$
#
PORTNAME=       aws-sigv4
PORTVERSION=    1.1.0
CATEGORIES=     rubygems
MAINTAINER=     none@FreeBSD.org
MASTER_SITES=   RG
COMMENT=       AWS Signature Version 4 library.

RUN_DEPENDS+= rubygem-aws-eventstream>=1.0.2:ruby/rubygem-aws-eventstream

USES=           gem
USE_RUBY=       yes

NO_ARCH=        yes

.include <bsd.port.mk>
#EOF
