#
# $Id: Makefile 2196 2009-08-20 23:12:17Z root $
# $URL$
#
PORTNAME=	expat
PORTVERSION=	2.1.0
CATEGORIES=	textproc
PKGNAMEPREFIX=	lib
MASTER_SITES=	SF

MAINTAINER=	onborodin@gmail.com
COMMENT=	XML 1.0 parser written in C

GNU_CONFIGURE=	yes
USES+=		gmake
ALL_TARGET=	default
INSTALLS_SHLIB=	yes
MAKE_ENV+=	SHELL="/bin/sh"

.include <bsd.port.mk>
#EOF
