#
# $Id$
#
PORTNAME=	Net-CUPS
PORTVERSION=	0.61
CATEGORIES=	print perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	vg@FreeBSD.org
COMMENT=	Interface to the CUPS API

LIB_DEPENDS+=	libcupsimage.so:print/cups-base
LIB_DEPENDS+=	libcupsfilters.so:print/cups-filters

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
#EOF
