# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: head/devel/py-zope.exceptions/Makefile 412346 2016-04-01 14:00:51Z mat $

PORTNAME=	zope.exceptions
PORTVERSION=	4.0.0.1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DIST_SUBDIR=	zope

MAINTAINER=	zope@FreeBSD.org
COMMENT=	General Zope Exceptions

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}zope.interface>0:python/py-zope.interface@${PY_FLAVOR}

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
#EOF
