# Created by: Johannes Jost Meixner <xmj@FreeBSD.org>
# $FreeBSD: head/textproc/rubygem-sass-rails-rails52/Makefile 513360 2019-09-30 11:31:34Z sunpoet $

PORTNAME=	sass-rails
PORTVERSION=	5.1.0
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Sass adapter for the Rails asset pipeline

RUN_DEPENDS=	rubygem-sassc-rails>=2.1.1:rails5/rubygem-sassc-rails

USES=		gem
USE_RUBY=	yes

NO_ARCH=	yes

.include <bsd.port.mk>
