# $FreeBSD: head/devel/rubygem-rails-i18n-rails52/Makefile 515232 2019-10-22 23:34:46Z sunpoet $

PORTNAME=	i18n-tasks
PORTVERSION=	0.9.29
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Common locale data and translations for Rails i18n

RUN_DEPENDS=	\
		rubygem-activesupport>=4.0:rails6/rubygem-activesupport \
		rubygem-rails-i18n>=6.0:rails6/rubygem-rails-i18n \
		rubygem-ast>=2.1:ruby/rubygem-ast \
		rubygem-erubi>=0:ruby/rubygem-erubi \
		rubygem-highline>=1.0:ruby/rubygem-highline \
		rubygem-i18n>=0:ruby/rubygem-i18n \
		rubygem-parser>=2.2:ruby/rubygem-parser \
		rubygem-rainbow>=2.2.2:ruby/rubygem-rainbow \
		rubygem-terminal-table>=1.5:ruby/rubygem-terminal-table


USES=		gem
USE_RUBY=	yes

NO_ARCH=	yes

.include <bsd.port.mk>
