# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: head/net/py-zope.proxy/Makefile 412348 2016-04-01 14:17:44Z mat $

PORTNAME=	zope.proxy
PORTVERSION=	4.1.3
CATEGORIES=	net python zope
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DIST_SUBDIR=	zope

MAINTAINER=	zope@FreeBSD.org
COMMENT=	Generic Transparent Proxies

BUILD_DEPENDS=	${PYTHON_PKGNAMEPREFIX}zope.interface>=3.3.0:python/py-zope.interface@${PY_FLAVOR}

USES=		python zip
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
#EOF
