#
# $Id$
#
PORTNAME=       aws-sdk-ec2
PORTVERSION=    1.118.0
CATEGORIES=     rubygems
MAINTAINER=     none@FreeBSD.org
MASTER_SITES=   RG
COMMENT=       AWS SDK for Ruby - Amazon EC2

RUN_DEPENDS+= rubygem-aws-sigv4>=1.1:ruby/rubygem-aws-sigv4
RUN_DEPENDS+= rubygem-aws-sdk-core>=3.71.0:ruby/rubygem-aws-sdk-core

USES=           gem
USE_RUBY=       yes

NO_ARCH=        yes

.include <bsd.port.mk>
#EOF
