# Created by: Daniel Roethlisberger <daniel@roe.ch>
# $FreeBSD: head/www/rubygem-sinatra/Makefile 441035 2017-05-16 18:21:55Z sunpoet $

PORTNAME=	sinatra-logger
PORTVERSION=	0.3.2
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Sinatra Logger

RUN_DEPENDS=	rubygem-sinatra>=0:ruby/rubygem-sinatra \
		rubygem-semantic_logger>=0:ruby/rubygem-semantic_logger

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
