# $FreeBSD: head/mail/rubygem-mini_mime/Makefile 506299 2019-07-09 18:20:13Z sunpoet $

PORTNAME=	mini_mime
PORTVERSION=	1.0.2
CATEGORIES=	mail rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Lightweight mime type lookup toy


USES=		gem
USE_RUBY=	yes

NO_ARCH=	yes

.include <bsd.port.mk>
