# Created by: Roland van Laar <roland@micite.net>
# $FreeBSD: head/databases/py-sqlparse/Makefile 527575 2020-03-01 18:18:22Z sunpoet $

PORTNAME=	sqlparse
PORTVERSION=	0.3.1
CATEGORIES=	databases python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Non-validating SQL parser for Python

USES=		python
USE_PYTHON=	autoplist concurrent distutils

NO_ARCH=	yes

.include <bsd.port.mk>
