# $FreeBSD:ruby/Makefile 434785 2017-02-25 09:55:57Z sunpoet $

PORTNAME=	arel
PORTVERSION=	6.0.4
CATEGORIES=	databases rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	6

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Relational Algebra for Ruby


NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
