--- ./application/views/auth/setup.phtml.orig	2016-04-11 19:28:04.000000000 +0200
+++ ./application/views/auth/setup.phtml	2016-07-19 15:37:04.964670000 +0200
@@ -21,7 +21,7 @@
             secure, you are authorised to complete the install procedure and for cookie security. 
             To proceed, please set the following <strong>randomly generated</strong> salts 
             at the top of the <code>[user]</code> section of the following file: 
-            <code>application/configs/application.ini</code>.
+            <code>application/config/application.ini</code>.
             </p>
             
             <pre>securitysalt                       = "{$randomSalt|htmlentities}"
