--- ./application/views/mailbox/list.phtml.orig	2016-04-11 19:28:04.000000000 +0200
+++ ./application/views/mailbox/list.phtml	2016-07-19 15:37:04.965726000 +0200
@@ -38,6 +38,8 @@
                 <th>Size ({$size_multiplier})</th>
             {/if}
             <th>Domain</th>
+            <th>Created</th>
+            <th>LastLogin</th>
             <th width="55">Active</th>
             <th width="140"></th>
         </tr>
@@ -58,6 +60,11 @@
                 </td>
             {/if}
             <td>{$mbox.domain}</td>
+            <td>{$mbox.created->format("Y-M-d")}</td>
+            <td>{if $mbox.lastlogin}
+                      {$mbox.lastlogin->format("Y-M-d")}
+                {/if}
+            </td>
             <td>
                 <div id="throb-toggle-active-{$mbox.id}" style="float: right;"></div>
                 <span id="toggle-active-{$mbox.id}" onclick="toggleActive( 'toggle-active-{$mbox.id}', {$mbox.id} );" class="btn btn-mini {if $mbox.active}btn-success{else}btn-danger{/if}">{$mbox.active|yesno}</span>
