# Created by: jupengfei <jupengfei@gmail.com>
# $FreeBSD: head/net/p5-Net-Traceroute-PurePerl/Makefile 481365 2018-10-06 13:06:42Z des $

PORTNAME=	Net-Traceroute-PurePerl
PORTVERSION=	0.10
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Traceroute(1) functionality in perl via raw sockets

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS=	p5-Net-Traceroute>=0:perl/p5-Net-Traceroute

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
