# Created by: TERAMOTO Masahiro <markun@onohara.to>
# $FreeBSD:ruby/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	htmlentities
PORTVERSION=	4.3.4
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	markun@onohara.to
COMMENT=	HTML entity encoding and decoding for Ruby


NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
