# Created by: Denis Pokataev <catone@cpan.org>
# $FreeBSD: head/net/p5-XML-RPC/Makefile 412348 2016-04-01 14:17:44Z mat $

PORTNAME=	XML-RPC
PORTVERSION=	0.9
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	culot@FreeBSD.org
COMMENT=	Pure Perl implementation for an XML-RPC client and server

BUILD_DEPENDS+=	p5-libwww>=0:perl/p5-libwww
UILD_DEPENDS+=	p5-XML-TreePP>=0:perl/p5-XML-TreePP
RUN_DEPENDS+=	p5-libwww>=0:perl/p5-libwww
RUN_DEPENDS+=	p5-XML-TreePP>=0:perl/p5-XML-TreePP

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
#EOF
