# Created by: Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-bindex/Makefile 506452 2019-07-12 11:02:09Z sunpoet $

PORTNAME=	bindex
PORTVERSION=	0.8.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Bindings for your Ruby exceptions

USES=		gem
USE_RUBY=	yes

.include <bsd.port.mk>
