
PORTNAME=	gdbm
PORTVERSION=	1.8.3
CATEGORIES=	databases
MASTER_SITES=	${MASTER_SITE_GNU}
MASTER_SITE_SUBDIR=	${PORTNAME}
PKGNAMEPREFIX=	lib

MAINTAINER=	onborodin@gmail.com
COMMENT=	The GNU database manager

USES+=		gmake
GNU_CONFIGURE=	yes
INSTALLS_SHLIB=	yes

PLIST_FILES+=	man/man3/gdbm.3.gz
INFO=	gdbm

.include <bsd.port.mk>
#EOF
