#!/bin/sh

set -x

case $2 in 
    DEINSTALL)
	rm -f ${PKG_PREFIX}/share/pear/.depdb
	rm -f ${PKG_PREFIX}/share/pear/.depdblock
	rm -f ${PKG_PREFIX}/share/pear/.filemap
	rm -f ${PKG_PREFIX}/share/pear/.lock
	;;
    POST-DEINSTALL)
	;;
esac
exit 0
#EOF
