# Created by: Johannes Dieterich <jmd@FreeBSD.org>
# $FreeBSD: head/graphics/gpu-firmware-kmod/Makefile 514545 2019-10-15 16:23:05Z jmd $

PORTNAME=	gpu-firmware-kmod
PORTVERSION=	g20200130
CATEGORIES=	graphics

MAINTAINER=	jmd@FreeBSD.org
COMMENT=	Firmware modules for the linuxkpi-based KMS components

USES=		kmod uidfix

USE_GITHUB=	yes
GH_ACCOUNT=	FreeBSDDesktop
GH_PROJECT=	kms-firmware
GH_TAGNAME=	c9eb7f3

.include <bsd.port.mk>
