#
# $Id: Makefile 2439 2009-09-14 20:39:45Z root $
# $URL: file:///usr2/svn/ports5/graphics-libs/libart2/Makefile $
#
PORTNAME=	libart
PORTVERSION=	2.3.21
CATEGORIES=	graphics
MASTER_SITES=	${MASTER_SITE_GNOME}
MASTER_SITE_SUBDIR=	sources/${PORTNAME}_lgpl/${PORTVERSION:R}
DISTNAME=	${PORTNAME}_lgpl-${PORTVERSION}

MAINTAINER=	onborodin@gmail.com
COMMENT=	Library for high-performance 2D graphics

USES+=		tar:bzip2
INSTALLS_SHLIB=	yes
GNU_CONFIGURE=	yes
USES+=		gmake

.include <bsd.port.mk>
#EOF
