# Created by: Johannes Meixner <xmj@FreeBSD.org>
# $FreeBSD:ruby/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	rails-deprecated_sanitizer
PORTVERSION=	1.0.3
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Deprecated sanitizer API extracted from Action View


RUN_DEPENDS=	rubygem-activesupport4>=4.2.1:ruby/rubygem-activesupport4

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
