# Created by: osa
# $FreeBSD: head/devel/lua-cjson/Makefile 531700 2020-04-14 15:49:36Z mat $

PORTNAME=	cjson
PORTVERSION=	2.1.0
CATEGORIES=	devel
MASTER_SITES=	http://www.kyne.com.au/~mark/software/download/
PKGNAMEPREFIX=	${LUA_PKGNAMEPREFIX}-
DISTNAME=	lua-cjson-${PORTVERSION}

MAINTAINER=	osa@FreeBSD.org
COMMENT=	Fast JSON parsing and encoding support for Lua

USES=		lua:module

.include <bsd.port.mk>
