# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD:perl/Makefile 412346 2016-04-01 14:00:51Z mat $

PORTNAME=	Exporter-Tiny
PORTVERSION=	0.042
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Exporter with features of Sub::Exporter but only core dependencies

USE_PERL5=	configure
USES=		perl5

.include <bsd.port.mk>
#EOF

