#
# $Id$
#
PORTNAME=	Mail_Mime
PORTVERSION=	1.10.0
CATEGORIES=	mail www pear

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	PEAR classes to create and decode MIME messages

USES=		pear
NO_ARCH=	yes

.include <bsd.port.mk>
#EOF
