# Created by: Olivier Girard <Olivier.Girard@univ-angers.fr>
# $FreeBSD: head/mail/p5-MIME-Charset/Makefile 382468 2015-03-28 12:17:29Z sunpoet $

PORTNAME=	MIME-Charset
PORTVERSION=	1.012
CATEGORIES=	mail perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

# blanket update approval granted, see pr136540
MAINTAINER=	Olivier.Girard@univ-angers.fr
COMMENT=	Charset Informations for MIME

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
