# Created by: Marco Steinbach <coco@webdev.c0c0.intra>
# $FreeBSD: head/net/sqtop/Makefile 357080 2014-06-09 00:34:49Z danilo $

PORTNAME=	sqtop
DISTVERSION=	2013-12-17
CATEGORIES=	net
MASTER_SITES=	GOOGLE_CODE

MAINTAINER=	coco@executive-computing.de
COMMENT=	Console-based display of Squid proxy connections

USES=		tar:bzip2 gmake
GNU_CONFIGURE=	yes
CONFIGURE_ARGS+= --enable-ui

.include <bsd.port.mk>
#EOF

