#
# $Id$
#
PORTNAME=       aws-sdk-route53domains
PORTVERSION=    1.18.0
CATEGORIES=     rubygems
MAINTAINER=     none@FreeBSD.org
MASTER_SITES=   RG
COMMENT=       AWS SDK for Ruby - Amazon Route 53 Domains

RUN_DEPENDS+= rubygem-aws-sdk-core>=3.71.0:ruby/rubygem-aws-sdk-core
RUN_DEPENDS+= rubygem-aws-sigv4>=1.1:ruby/rubygem-aws-sigv4

USES=           gem
USE_RUBY=       yes

NO_ARCH=        yes

.include <bsd.port.mk>
#EOF
