#
# $Id$
#
PORTNAME=	le
PORTVERSION=	1.16.5
CATEGORIES=	editors
#MASTER_SITES+=	ftp://ftp.yar.ru/pub/source/le/%SUBDIR%/
#MASTER_SITES+=	http://mirrors.rit.edu/zi/
MASTER_SITE_SUBDIR=	. old
MASTER_SITES=	http://lav.yar.ru/download/${PORTNAME}/ ZI


MAINTAINER=	zi@FreeBSD.org
COMMENT=	Text editor with block and binary operations


USES=		tar:bzip2
GNU_CONFIGURE=	yes
MAKE_JOBS_UNSAFE=	yes

.include <bsd.port.mk>
#EOF
