#
# $Id$
#
PORTNAME=	Digest-SHA1
PORTVERSION=	2.13
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl interface to the SHA-1 Algorithm

USES=		perl5
USE_PERL5=	configure
PERL_CONFIGURE=	yes
USE_GMAKE=	yes

.include <bsd.port.mk>
#EOF

