#
# $Id$
#
PORTNAME=	libmpdclient
PORTVERSION=	2.9
CATEGORIES=	audio
MASTER_SITES=	http://www.musicpd.org/download/libmpdclient/2/


MAINTAINER=	onborodin@gmail.com
COMMENT=	API library for interfacing MPD

USES+=		tar:xz
GNU_CONFIGURE=	yes
USES+=		gmake
USE_LDCONFIG=	yes
CONFIGURE_ARGS=	--disable-documentation


.include <bsd.port.mk>
#EOF

