#
# $Id$
#
PORTNAME=       aws-sdk-importexport
PORTVERSION=    1.16.0
CATEGORIES=     rubygems
MAINTAINER=     none@FreeBSD.org
MASTER_SITES=   RG
COMMENT=       AWS SDK for Ruby - AWS Import/Export

RUN_DEPENDS+= rubygem-aws-sdk-core>=3.71.0:ruby/rubygem-aws-sdk-core
RUN_DEPENDS+= rubygem-aws-sigv2>=1.0:ruby/rubygem-aws-sigv2

USES=           gem
USE_RUBY=       yes

NO_ARCH=        yes

.include <bsd.port.mk>
#EOF
