#
# $Id$
#
PORTNAME=	BSD-stat
PORTVERSION=	1.35
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Stat() with BSD 4.4 extensions

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
#EOF
