#
# $Id$
#
PORTNAME=	URI-Escape-XS
PORTVERSION=	0.13
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	culot@FreeBSD.org
COMMENT=	Drop-In replacement for URI::Escape in XS

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
#EOF
