#
# $Id$
#
PORTNAME=	Socket6
PORTVERSION=	0.25
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=CPAN:UMEMOTO
PKGNAMEPREFIX=	p5-

MAINTAINER=	ume@FreeBSD.org
COMMENT=	IPv6 related part of the C socket.h defines and structure manipulators

USES=		perl5
USE_PERL5=	configure
CONFIGURE_ENV+=	CC="${CC}"

.include <bsd.port.mk>
#EOF

