# Created by: Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/databases/rubygem-dalli/Makefile 508633 2019-08-11 16:46:08Z sunpoet $

PORTNAME=	dalli
PORTVERSION=	2.7.10
CATEGORIES=	databases rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	High performance memcached client for Ruby


USES=		gem
USE_RUBY=	yes

NO_ARCH=	yes

.include <bsd.port.mk>
