#
# $Id$
#
PORTNAME=	rails6
PORTVERSION=	1.0
CATEGORIES=	devel net

MAINTAINER=	gnome@FreeBSD.org
COMMENT=	meta-port Ruby on Rails 

USES=		metaport

RUN_DEPENDS=    rubygem-rails>=6.0:rails6/rubygem-rails \
	        rubygem-rails-i18n>=0:rails6/rubygem-rails-i18n \
	        rubygem-i18n-tasks>=0:rails6/rubygem-i18n-tasks \
	        rubygem-faker>=0.7:ruby/rubygem-faker \
	        rubygem-bcrypt>=0:ruby/rubygem-bcrypt \
	        rubygem-irb>=0:ruby/rubygem-irb \
	        rubygem-mail>=0:ruby/rubygem-mail \
	        rubygem-msgpack>=0:ruby/rubygem-msgpack \
	        rubygem-net-ping>=0:ruby/rubygem-net-ping \
	        rubygem-net-scp>=0:ruby/rubygem-net-scp \
	        rubygem-net-sftp>=0:ruby/rubygem-net-sftp \
	        rubygem-net-ssh>=0:ruby/rubygem-net-ssh \
	        rubygem-byebug>=0:ruby/rubygem-byebug \
	        rubygem-pry>=0:ruby/rubygem-pry


.include <bsd.port.mk>
#EOF
