# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD:ruby/Makefile 440192 2017-05-05 16:05:45Z sunpoet $

PORTNAME=	protected_attributes
PORTVERSION=	1.1.4
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Protect attributes from mass assignment


RUN_DEPENDS=	rubygem-activemodel4>=4.0.1:ruby/rubygem-activemodel4

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
