PORTNAME=	markdown
PORTVERSION=	3.3.7
CATEGORIES=	textproc python
MASTER_SITES=	PYPI
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	Markdown-${PORTVERSION}

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Python implementation of Markdown
WWW=		https://github.com/Python-Markdown/markdown

USES=		python:3.6+
USE_PYTHON=	autoplist concurrent distutils 

NO_ARCH=	yes

.include <bsd.port.mk>
