# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD:ruby/Makefile 437309 2017-03-30 15:13:28Z sunpoet $

PORTNAME=	rbpdf-font
PORTVERSION=	1.19.1
CATEGORIES=	print rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	RBPDF font files


NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
