#
# $Id$
#
PORTNAME=       aws-eventstream
PORTVERSION=    1.0.3
CATEGORIES=     rubygems
MAINTAINER=     none@FreeBSD.org
MASTER_SITES=   RG
COMMENT=       AWS Event Stream Library


USES=           gem
USE_RUBY=       yes

NO_ARCH=        yes

.include <bsd.port.mk>
#EOF
