# Created by: Choe, Cheng-Dae
# $FreeBSD: head/devel/py-configobj/Makefile 412346 2016-04-01 14:00:51Z mat $

PORTNAME=	configobj
PORTVERSION=	5.0.6
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	Simple but powerful config file reader and writer

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}six>0:python/py-six@${PY_FLAVOR}

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
#EOF
