#ifndef _PKG_CONFIG_H
#define _PKG_CONFIG_H
#define HAVE_ARC4RANDOM 1
/* #undef HAVE_ARC4RANDOM_STIR */
#define HAVE_ARCHIVE_READ_OPEN 1
#define HAVE_ARCHIVE_WRITE_ADD_FILTER_ZSTD 1
#define HAVE_ATOMIC_BUILTINS 1
/* #undef HAVE_BASENAME_R */
/* #undef HAVE_BSD_ERR_H */
/* #undef HAVE_BSD_LIBUTIL_H */
/* #undef HAVE_BSD_READPASSPHRASE_H */
/* #undef HAVE_BSD_STDIO_H */
/* #undef HAVE_BSD_STRING_H */
/* #undef HAVE_BSD_STRLIB_H */
/* #undef HAVE_BSD_SYS_CDEFS_H */
/* #undef HAVE_BSD_UNISTD_H */
#define HAVE_BZ2_BZREADOPEN 1
#define HAVE_CAPSICUM 1
#define HAVE_CAP_SANDBOXED 1
#define HAVE_CHFLAGSAT 1
#define HAVE_CLOSEFROM 1
#define HAVE_DECL_BE16DEC 1
#define HAVE_DECL_BE16ENC 1
#define HAVE_DECL_BE32DEC 1
#define HAVE_DECL_BE32ENC 1
#define HAVE_DECL_BE64DEC 1
#define HAVE_DECL_BE64ENC 1
#define HAVE_DECL_F_CLOSEM 0
#define HAVE_DECL_HUMANIZE_NUMBER 1
#define HAVE_DECL_LE16DEC 1
#define HAVE_DECL_LE16ENC 1
#define HAVE_DECL_LE32DEC 1
#define HAVE_DECL_LE32ENC 1
#define HAVE_DECL_LE64DEC 1
#define HAVE_DECL_LE64ENC 1
#define HAVE_DECL_SOCK_SEQPACKET 1
#define HAVE_DIRENT_H 1
#define HAVE_DIRFD 1
#define HAVE_DLCLOSE 1
#define HAVE_EACCESS 1
#define HAVE_ELF_HINTS_H 1
/* #undef HAVE_ELF_NOTE */
/* #undef HAVE_ENDIAN_H */
#define HAVE_FACCESSAT 1
#define HAVE_FCHOWN 1
#define HAVE_FCNTL_H 1
#define HAVE_FDATASYNC 1
#define HAVE_FFLAGSTOSTR 1
#define HAVE_FOPENCOOKIE 1
#define HAVE_FSTATAT 1
#define HAVE_FSTATFS 1
#define HAVE_FTS_OPEN 1
#define HAVE_FUNOPEN 1
#define HAVE_GELF_GETEHDR 1
#define HAVE_GELF_H 1
#define HAVE_GETPROGNAME 1
#define HAVE_GMTIME_R 1
#define HAVE_HUMANIZE_NUMBER 1
#define HAVE_INTTYPES_H 1
#define HAVE_ISNAN 1
#define HAVE_JAIL_GETID 1
#define HAVE_LIBELF 1
#define HAVE_LIBELF_H 1
#define HAVE_LIBJAIL 1
#define HAVE_LIBMD 1
#define HAVE_LIBUTIL 1
#define HAVE_LIBUTIL_H 1
#define HAVE_LINK_H 1
#define HAVE_LOCALTIME_R 1
#define HAVE_LSTAT 1
#define HAVE_LZMA_VERSION_STRING 1
#define HAVE_MACHINE_ENDIAN_H 1
#define HAVE_MEMMOVE 1
#define HAVE_NETINET_IN_H 1
#define HAVE_OPENAT 1
#define HAVE_OSRELDATE_H 1
#define HAVE_PKG_CONFIG 1
#define HAVE_PREAD 1
/* #undef HAVE_PROC_PID */
#define HAVE_PWRITE 1
#define HAVE_READLINK 1
#define HAVE_READLINKAT 1
#define HAVE_READPASSPHRASE_H 1
#define HAVE_REALLOCARRAY 1
#define HAVE_SHA256_DATA 1
#define HAVE_STATIC 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRCHRNUL 1
#define HAVE_STRERROR_R 1
#define HAVE_STRNSTR 1
#define HAVE_STRTOFFLAGS 1
#define HAVE_STRTONUM 1
#define HAVE_STRUCT_SOCKADDR_IN_SIN_LEN 1
#define HAVE_STRUCT_STAT_ST_FLAGS 1
#define HAVE_STRUCT_STAT_ST_MTIM 1
#define HAVE_SYSCONF 1
#define HAVE_SYS_CAPSICUM_H 1
#define HAVE_SYS_ELF_COMMON_H 1
#define HAVE_SYS_ENDIAN_H 1
#define HAVE_SYS_PROCCTL_H 1
#define HAVE_SYS_SOCKET_H 1
/* #undef HAVE_SYS_STATFS_H */
#define HAVE_SYS_STATVFS_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_UNLINKAT 1
#define HAVE_USLEEP 1
#define HAVE_UTIMENSAT 1
#define HAVE_ZLIBVERSION 1
#define HAVE_ZSTD_VERSIONNUMBER 1
#define HAVE___RES_QUERY 1
#define HAVE___RES_SETSERVERS 1
#endif
