# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/textproc/p5-XML-SAX-Base/Makefile 376745 2015-01-11 13:27:11Z sunpoet $

PORTNAME=	XML-SAX-Base
PORTVERSION=	1.08
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Base class SAX Drivers and Filters


CONFLICTS_INSTALL=	p5-XML-SAX-0.[0-8]* p5-XML-SAX-0.9[0-8]*

USE_PERL5=	configure
USES=		perl5

.include <bsd.port.mk>
#EOF
