#
# $Id$
#
PORTNAME=	jansson
PORTVERSION=	2.7
CATEGORIES=	devel
MASTER_SITES=	http://www.digip.org/jansson/releases/
PKGNAMEPREFIX=	lib

MAINTAINER=	vanilla@FreeBSD.org
COMMENT=	C library for encoding, decoding, and manipulating JSON data

USES=		gmake tar:bzip2
USE_LDCONFIG=	yes
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
#EOF
