#
# $Id$
#
PORTNAME=	XML-XPath
PORTVERSION=	1.36
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Modules for parsing and evaluating XPath statements

BUILD_DEPENDS=	p5-XML-Parser>=2.23:perl/p5-XML-Parser
RUN_DEPENDS:=	${BUILD_DEPENDS}
#TEST_DEPENDS=	p5-Path-Tiny>=0.076:devel/p5-Path-Tiny

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
#EOF
