# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/textproc/p5-CSS-Minifier/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	CSS-Minifier
PORTVERSION=	0.01
CATEGORIES=	textproc www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Perl extension for minifying CSS


USE_PERL5=	configure
USES=		perl5

.include <bsd.port.mk>
#EOF
